version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
    ports:
      - "5432:5432"

  django:
    build: ./django-hallow-ethical-hacking
    command: gunicorn --bind :8000 --workers 3 DjangoHallowEthicalHacking.wsgi 
    volumes:
      - django_static:/app/static
    env_file:
      - ./django-hallow-ethical-hacking/.env
    depends_on:
      - db
      - redis

  celery:
    build: ./django-hallow-ethical-hacking
    command: celery -A DjangoHallowEthicalHacking worker -l info
    depends_on:
      - django
      - redis

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - ./redis_data:/data

  vue:
    build:
      context: ./vue-hallow-ethical-hacking
      dockerfile: ./Dockerfile
    volumes:
      - vue_dst:/app/dist
    depends_on:
      - django

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - django_static:/usr/share/nginx/html/static
      - vue_dst:/usr/share/nginx/html
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - django
      - vue

volumes:
  django_static:
  vue_dst: