services:

  db:
    image: postgres:14.13-alpine
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - internal

  django:
    build: ./django-hallow-ethical-hacking
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django_static:/app/static
    env_file:
      - ./django-hallow-ethical-hacking/.env
    depends_on:
      - db
      - redis
    ports:
      - 5678:5678
    networks:
      - internal

  celery:
    build: ./django-hallow-ethical-hacking
    container_name: celery
    command: celery -A DjangoHallowEthicalHacking worker -l info
    depends_on:
      - django
      - redis
    networks:
      - internal

  celery-beat:
    build: ./django-hallow-ethical-hacking
    container_name: celery-beat
    command: celery -A DjangoHallowEthicalHacking beat -l info
    depends_on:
      - django
      - redis
    networks:
      - internal

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    volumes:
      - ./redis_data:/data
    networks:
      - internal

  vue:
    build:
      context: ./vue-hallow-ethical-hacking
      dockerfile: ./Dockerfile
    container_name: vue
    volumes:
      - vue_dst:/app/dist
    depends_on:
      - django
    networks:
      - internal

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    volumes:
      - django_static:/usr/share/nginx/html/static
      - vue_dst:/usr/share/nginx/html
    restart: unless-stopped
    depends_on: 
      - django
      - vue
    ports:
      - 80:80
    networks:
      - internal
      - proxy

volumes:
  django_static:
  vue_dst:

networks:
  internal:
  proxy:
    external: true